# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ZincBlog
# subtitle: 'ZincBlog is not code Blog'
description: '一鲸落而万物生，繁花谢而万物新'
keywords:
author: szoloa
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://szoloa.top
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://gitee.com/szoloa/blog.git # https://github.com/szoloa/szoloa.github.io.git  #你的仓库地址
  branch: main
markdown: 'commonmark'

# 图标
nav:
  logo: /images/usage/icon.jpg
  display_title: true
  fixed: false # fixed navigation bar
favicon:  /images/usage/favicon-32x32-next.ico

# 代码主题
highlight_theme: light
highlight_copy: true
highlight_shrink: false #代码框展开，有>点击按钮

# 主题节选
index_post_content:
  method: 2
  length: 500

# 文章封面
cover:
  # 是否显示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面显示的位置
  # 三个值可配置 left , right , both
  position: both
  # 当没有设置cover时，默认的封面显示
  default_cover: https://image.baidu.com/search/down?url=https://wx3.sinaimg.cn/mw690/00817ymegy1hcr7d1y6n0j32yo1o01ky.jpg # /images/usage/default_top_img.jpg #'linear-gradient(20deg, #0062be, #925696, #cc426e, #fb0347)'


# 顶部图
index_img: https://image.baidu.com/search/down?url=https://wx3.sinaimg.cn/large/00817ymegy1hcs5932lj2j30xc0o3nag.jpg # /images/usage/index_img_1.jpg
default_top_img: https://image.baidu.com/search/down?url=https://wx3.sinaimg.cn/mw690/00817ymegy1hcr7d1y6n0j32yo1o01ky.jpg # /images/usage/default_top_img.jpg



# 目录
toc:
  post: false
  page: false
  number: false
  expand: false
  style_simple: false # for post
  scroll_percent: false

# 分页按钮
post_pagination: false

# 头像
avatar:
  img: https://image.baidu.com/search/down?url=https://wx2.sinaimg.cn/mw2000/00817ymegy1hcs4upqz3oj313b13b15i.jpg # /images/usage/avatar.gif
  effect: false # 头像会一直转圈

# 博客底部
footer:
  owner:
    enable: true
    since: 2023
custom_text: 欢迎来到我的博客！


menu:
  主页: / || fas fa-home
  博文 || fa fa-graduation-cap:
    分类: /categories/ || fa fa-archive
    标签: /tags/ || fa fa-tags
    归档: /archives/ || fa fa-folder-open
  杂谈: /share/ || fa fa-comments
  图库: /gallery/ || fas fa-images
  友链: /link/ || fa fa-list
  关于: /about/ || fas fa-heart  
  

# 夜间模式
darkmode:
  enable: true
  # dark mode和 light mode切换按钮
  button: true
  autoChangeMode: false
# 滚动条
rightside_scroll_percent: false

# 侧边栏设置
aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: left # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: 关注
      link: https://github.com/szoloa
  card_announcement:
    enable: false
    content: 
  card_recent_post:
    enable: false
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
    orderby: random # Order of tags, random/name/length
    order: 1 # Sort of order. 1, asc for ascending; -1, desc for descending
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works

# 网站统计
busuanzi:
  site_uv: false
  site_pv: false
  page_pv: true
runtimeshow:
  enable: false
  publish_date: 28/3/2023 00:00:00  
  ##网页开通时间
  #格式: 月/日/年 时间
  #也可以写成 年/月/日 时间


# 主页subtitle
subtitle: 
  enable: true
  effect: false
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 150 # type speed in milliseconds
  backSpeed: 50 # backspacing speed in milliseconds
  loop: false
  source: false
  # 如果关闭打字效果，subtitle 只会显示 sub 的第一行文字
  sub: 
    - 'ZincBlog is not code Blog'


# 社交
social:
  fab fa-github: https://github.com/szoloa || Github
  fas fa-envelope: mailto:szoloa@hotmail.com || Email
# 打赏
reward:
  enable: true
  QR_code:
    - img: /images/usage/wechatpay.jpg
      link:
      text: 微信
    - img: /images/usage/alipay.jpg
      link:
      text: 支付宝


# 版权
post_copyright:
  enable: false
  decode: false
  author_href:
  # license: CC BY-NC-SA 4.0
  # license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

mathjax:
  enable: true
  # true 表示每一頁都加載mathjax.js
  # false 需要時加載，須在使用的Markdown Front-matter 加上 mathjax: true
  per_page: false

# 评论系统
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use: Valine
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img
  card_post_count: false # Display comment count in Home Page
valine:
  appId: R1JnQN4BUfienmRFnivsgZ1U-gzGzoHsz
  appKey: yhBgghSEVWa9KXNd5VbrOma7
  avatar: ysYWwwsVL7BmJosVzgwzPHwx # gravatar style https://valine.js.org/#/avatar
  serverURLs: # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
  bg: # valine background
  visitor: true
  option:

# A simple 404 page
error_404:
  enable: true
  subtitle: "頁面沒有找到"
  background: 

# 大图模式
medium_zoom: true