# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ZincBlog
# subtitle: 'ZincBlog is not code Blog'
description: '一鲸落而万物生，繁花谢而万物新'
keywords:
author: szoloa
language: zh-CN
timezone: 'Asia/Shanghai'


abbrlink:
  alg: crc32      #support crc16(default) and crc32
  rep: hex    
# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://szoloa.top
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://github.com/szoloa/szoloa.github.io.git  #你的仓库地址
  branch: main
markdown: 'commonmark'

# 图标
nav:
  logo: https://image.baidu.com/search/down?url=https://wx2.sinaimg.cn/mw690/00817ymegy1hcs4vbg31yj30u00t4q5u.jpg # /images/usage/icon.jpg
  display_title: true
  fixed: false # fixed navigation bar
favicon: https://image.baidu.com/search/down?url=https://wx2.sinaimg.cn/mw690/00817ymegy1hcs4vbg31yj30u00t4q5u.jpg # /images/usage/favicon-32x32-next.ico

# 代码主题
highlight_theme: mac
highlight_copy: true
highlight_shrink: false #代码框展开，有>点击按钮

# 主题节选
index_post_content:
  method: 2
  length: 500

# 文章封面
cover:
  # 是否显示文章封面
  index_enable: false
  aside_enable: false
  archives_enable: false
  # 封面显示的位置
  # 三个值可配置 left , right , both
  position: both
  # 当没有设置cover时，默认的封面显示
  default_cover: https://image.baidu.com/search/down?url=https://wx2.sinaimg.cn/mw690/00817ymegy1hcz1f26a2nj32o01o0an0.jpg # /images/usage/default_top_img.jpg #'linear-gradient(20deg, #0062be, #925696, #cc426e, #fb0347)'


# 顶部图
index_img: https://image.baidu.com/search/down?url=https://wx3.sinaimg.cn/mw2000/00817ymegy1hcs5932lj2j30xc0o3nag.jpg # /images/usage/index_img_1.jpg
default_top_img: https://image.baidu.com/search/down?url=https://wx2.sinaimg.cn/mw2000/00817ymegy1hcz1f26a2nj32o01o0an0.jpg # /images/usage/default_top_img.jpg

# 目录
toc:
  post: true
  page: true
  number: true
  expand: false
  style_simple: false # for post
  scroll_percent: false
# 分页按钮
post_pagination: false

# 头像
avatar:
  img: https://image.baidu.com/search/down?url=https://wx2.sinaimg.cn/mw2000/00817ymegy1hcs4upqz3oj313b13b15i.jpg # /images/usage/avatar.gif
  effect: false # 头像会一直转圈

# 博客底部
footer:
  owner:
    enable: true
    since: 2023
  custom_text: <a href="https://icp.gov.moe/?keyword=20230449" target="_blank">萌ICP备20230449号</a>


menu:
  主页: / || fas fa-home
  博文: /archives/ || fa fa-folder-open
  杂谈: /share/ || fa fa-comments
  # 图库: /gallery/ || fas fa-images
  音乐: /music/ || fa fa-music
  友链: /link/ || fa fa-list
  关于: /about/ || fas fa-heart  
  

# 夜间模式
darkmode:
  enable: true
  # dark mode和 light mode切换按钮
  button: true
  autoChangeMode: false
# 滚动条
rightside_scroll_percent: false

# 侧边栏设置
aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  display:
    archive: false
    tag: true
    category: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: 关注
      link: https://github.com/szoloa
  card_announcement:
    enable: false
    content: 
  card_recent_post:
    enable: false
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: true 
    orderby: random # Order of tags, random/name/length
    order: 1 # Sort of order. 1, asc for ascending; -1, desc for descending
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: false
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works

# 网站统计
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

runtimeshow:
  enable: true
  # publish_date: 28/3/2023 00:00:00  
  publish_date: 2023/3/28 00:00:00
  ##网页开通时间
  #格式: 月/日/年 时间
  #也可以写成 年/月/日 时间


# 主页subtitle
subtitle: 
  enable: true
  effect: false
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 150 # type speed in milliseconds
  backSpeed: 50 # backspacing speed in milliseconds
  loop: false
  source: false
  # 如果关闭打字效果，subtitle 只会显示 sub 的第一行文字
  sub: 
    - 'ZincBlog is not code Blog'


# 社交
social:
  fab fa-github: https://github.com/szoloa || Github
  fas fa-envelope: mailto:szoloa@hotmail.com || Email


# 打赏
reward:
  enable: false
  QR_code:
    - img: https://image.baidu.com/search/down?url=https://wx1.sinaimg.cn/orj360/00817ymegy1hd6jr8be92j30dk0djmzg.jpg # /images/usage/wechatpay.jpg
      link:
      text: 微信
    - img: https://image.baidu.com/search/down?url=https://wx4.sinaimg.cn/orj360/00817ymegy1hd6jraapg2j30ih0ifacx.jpg # /images/usage/alipay.jpg
      link:
      text: 支付宝


# 版权
post_copyright:
  enable: false
  decode: false
  author_href:
  # license: CC BY-NC-SA 4.0
  # license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

mathjax:
  enable: true
  # true 表示每一頁都加載mathjax.js
  # false 需要時加載，須在使用的Markdown Front-matter 加上 mathjax: true
  per_page: false

# 评论系统
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use: Valine
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: false
  count: true # Display comment count in top_img
  card_post_count: false # Display comment count in Home Page


# valine:
#   appId: R1JnQN4BUfienmRFnivsgZ1U-gzGzoHsz
#   appKey: yhBgghSEVWa9KXNd5VbrOma7
#   avatar: ysYWwwsVL7BmJosVzgwzPHwx # gravatar style https://valine.js.org/#/avatar
#   serverURLs: # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
#   bg: # valine background
#   visitor: true
#   option: 

valine:
  appId: R1JnQN4BUfienmRFnivsgZ1U-gzGzoHsz
  appKey: yhBgghSEVWa9KXNd5VbrOma7
  avatar:  # gravatar style https://valine.js.org/#/avatar
  # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
  # visitor: true
  bg:  # valine background

# A simple 404 page
error_404:
  enable: true
  subtitle: "页面没有找到"
  background: https://image.baidu.com/search/down?url=https://wx3.sinaimg.cn/mw2000/00817ymegy1he1oyekkckj319s0qob29.jpg

# 大图模式
medium_zoom: true

note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: simple
  icons: true
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0

# 侧边栏 
post_meta:
  page:
    date_type: both # created or updated or both 主页文章日期是创建日或者更新日或都显示
    date_format: relative # date/relative 显示日期还是相对日期
    categories: true # true or false 主页是否显示分类
    tags: true # true or false 主页是否显示标签
    label: true # true or false 显示描述性文字
  post:
    date_type: both # created or updated or both 文章页日期是创建日或者更新日或都显示
    date_format: relative # date/relative 显示日期还是相对日期
    categories: true # true or false 文章页是否显示分类
    tags: true # true or false 文章页是否显示标签
    label: true # true or false 显示描述性文字
# 美化markdown标签

beautify:
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"

artitalk:
  enable: false
  appId: FMEBzdqKOZ9YeCxvXlheivJi-MdYXbMMI
  appKey: 8bWUuiQSnDWrguG21cm9uERA
  path:
  js:
  option:
  front_matter:

# 背景
canvas_nest:
  enable: false
  color: '0,0,255' #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: 0.7 # the opacity of line (0~1), default: 0.5.
  zIndex: -1 # z-index property of the background, default: -1.
  count: 99 # the number of lines, default: 99.
  mobile: false # false 手机端不显示 true 手机端显示
# 点击特效
fireworks:
  enable: false
  zIndex: 9999 # -1 or 9999
  mobile: false
# 加载动画
# preloader:
#   enable: true
#   source: 1
#   pace_css_url:

inject:
  head:
    # - <link rel="stylesheet" href="/xxx.css">
    - <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3543219094395505" crossorigin="anonymous"></script>
    - <meta name="baidu-site-verification" content="codeva-EDseRIsxK7" />
    - <link rel="stylesheet" href="/css/loading.css?1">
    # - <link rel="stylesheet" href="/css/anzhiyu.css?1">
    # - <link rel="stylesheet" href="/css/jsmind.css?1" />
    - <link rel="stylesheet" href="/css/font.css?1" />
  bottom:
    # - <script src="xxxx"></script>
    # - <script async data-pjax src="/js/anzhiyu.js"></script>
    # - <script src="/js/Meting2.js?1"></script>
    # - <script src="/js/jsmind.js?1"></script>

preloader:
  enable: true
  # source
  # 1. fullpage-loading
  # 2. pace (progress bar)
  # else all
  source: 2
  # pace theme (see https://codebyzach.github.io/pace/)
  pace_css_url: /css/progress_bar.css
  avatar: https://image.baidu.com/search/down?url=https://wx2.sinaimg.cn/mw2000/00817ymegy1hcs4upqz3oj313b13b15i.jpg # 自定义头像

# 谷歌广告
google_adsense:
  enable: false
  auto_ads: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: ca-pub-3543219094395505
  enable_page_level_ads: true
# 图片描述
photofigcaption: true
# 预加载
instantpage: false

# 底部
footer_bg: #28ae70

# 搜索
algolia_search:
  enable: false
  hits:
    per_page: 6
algolia:
  applicationID: '626PIBA3AO'
  apiKey: '492b572a1146f590ddedd020bb794bb2'
  indexName: 'ZincBlog'

# 全局字体设置
# Don't modify the following settings unless you know how they work (非必要不要修改)
font:
  global-font-size: 16px # 14px
  code-font-size: 16px
  font-family: AlibabaPuHuiTi-2-55-Regular, BlinkMacSystemFont, consolas, -apple-system, "Segoe UI", "Helvetica Neue", Lato, Roboto, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif
  code-font-family: consolas, Menlo, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif

blog_title_font:
  font_link: https://fonts.googleapis.com/css?family=Titillium+Web&display=swap
  font-family: Titillium Web, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft JhengHei', 'Microsoft YaHei', sans-serif
site_verification:
  # - name: google-site-verification
  #   content: xxxxxx
  # - name: baidu-site-verification
  #   content: xxxxxxx

# Inject the css and script (aplayer/meting)
aplayerInject:
  enable: true
  per_page: true


# hpptalk:
#   enable: true 
#   domain: zincblog.szoloa8796.workers.dev/
#   path:
#   limit:
#   start:
#   js:
#   css:
#   option:
#   front_matter:

local_search:
  enable: true
  # Preload the search data when the page loads.
  preload: true
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 3
  # Unescape html strings to the readable one.
  unescape: false
  CDN:

flink_style: butterfly

# Replace Broken Images (替換無法顯示的圖片)
error_img:
  flink: https://image.baidu.com/search/down?url=https://wx4.sinaimg.cn/mw690/00817ymegy1he9mqy49oyj30i20i2n0s.jpg  # 头像失效替换图
  post_page: https://image.baidu.com/search/down?url=https://wx3.sinaimg.cn/mw690/00817ymegy1he1oyekkckj319s0qob29.jpg # 站点缩略图


# Loading Animation (加载动画)

# tag-plugins-plus
# see https://akilar.top/posts/615e2dec/
tag_plugins:
  enable: true # 开关
  priority: 5 #过滤器优先权
  issues: false #issues标签依赖注入开关
  link:
    placeholder: /img/link.png #link_card标签默认的图标图片
  CDN:
    anima: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/font-awesome-animation.min.css #动画标签anima的依赖
    jquery: https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js #issues标签依赖
    issues: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/issues.js #issues标签依赖
    iconfont: //at.alicdn.com/t/font_2032782_8d5kxvn09md.js #参看https://akilar.top/posts/d2ebecef/
    carousel: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/carousel-touch.js
    tag_plugins_css: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/tag_plugins.css


wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

CDN:
  # The CDN provider of internal scripts (主题内部 js 的 cdn 配置)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # Dev version can only choose. ( dev版的主题只能设置为 local )
  internal_provider: local

  # The CDN provider of third party scripts (第三方 js 的 cdn 配置)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # when set it to local, you need to install hexo-butterfly-extjs
  third_party_provider: jsdelivr

  # Add version number to CDN, true or false  
  version: false

  # Custom format
  # For example: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format:

  option:
    # main_css:
    # main:
    # utils:
    # translate:
    # local_search:
    # algolia_js:
    # algolia_search:
    # instantsearch:
    # docsearch_js:
    # docsearch_css:
    # pjax:
    # gitalk:
    # gitalk_css:
    # blueimp_md5:
    # valine:
    # disqusjs:
    # disqusjs_css:
    # twikoo:
    # waline_js:
    # waline_css:
    # giscus:
    # sharejs:
    # sharejs_css:
    # mathjax:
    # katex:
    # katex_copytex:
    # mermaid:
    # canvas_ribbon:
    # canvas_fluttering_ribbon:
    # canvas_nest:
    # lazyload:
    # instantpage:
    # typed:
    # pangu:
    # fancybox_css:
    # fancybox:
    # medium_zoom:
    # snackbar_css:
    # snackbar:
    # activate_power_mode:
    # fireworks:
    # click_heart:
    # ClickShowText:
    # fontawesome:
    # flickr_justified_gallery_js:
    # flickr_justified_gallery_css:
    # aplayer_css:
    # aplayer_js:
    # meting_js:
    # prismjs_js:
    # prismjs_lineNumber_js:
    # prismjs_autoloader:
    # artalk_js:
    # artalk_css:
    # busuanzi:
    # abcjs_basic_js:
    # meting_js: https://npm.elemecdn.com/hexo-anzhiyu-music@1.0.1/assets/js/Meting2.min.js
